-- カラム定義を共有するためのSQLマクロ的アプローチ

-- 共通のカラム定義を関数として作成
CREATE OR REPLACE FUNCTION create_users_table(table_name text, id_column text, pass_column text) 
RETURNS void AS $$
BEGIN
  EXECUTE format('
    CREATE TABLE public.%I (
      %I bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      created_at timestamp with time zone NOT NULL DEFAULT now(),
      username character varying NOT NULL,
      %I character varying NOT NULL,
      CONSTRAINT %I_pkey PRIMARY KEY (%I),
      CONSTRAINT %I_username_key UNIQUE (username)
    ) TABLESPACE pg_default;
  ', 
  table_name, id_column, pass_column, table_name, id_column, table_name);
END;
$$ LANGUAGE plpgsql;

-- 既存のテーブルを削除（必要な場合）
-- DROP TABLE IF EXISTS public.customer_users;
-- DROP TABLE IF EXISTS public.admin_users;

-- 共通の関数を使用して各テーブルを作成
SELECT create_users_table('customer_users', 'customer_user_id', 'pass');
SELECT create_users_table('admin_users', 'admin_user_id', 'admin_pass');

-- 関数を削除（オプション）
DROP FUNCTION IF EXISTS create_users_table(text, text, text);

-- 注意: このスクリプトは既存のテーブルを再作成するため、
-- 既存のデータがある場合は事前にバックアップを取ってください。
